from commands.config_cmd import handle_config
from commands.account_cmd import handle_account
from commands.doc_cmd import handle_doc
from commands.edit_cmd import handle_edit
from commands.import_cmd import handle_import
from commands.list_cmd import handle_list
from commands.add_cmd import handle_add
from commands.report_cmd import handle_report
from commands.sensor_cmd import handle_sensor
